version: '2'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
#      MY_KEY: 123

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo


#  myapp:
#    build: .
#    ports:
#      - 8000
#    volumes:
#      - /C:/Users/Lars/KalleApplication/spring-docker-demo
#    environment:
#      MY_DATABASE_HOST: mongo
#      MY_DATABASE_USER: root
#      MY_DATABASE_PORT: 8081
#    depends_on:
#      - mongo
